filter:
    paths: 
        - src/*
    excluded_paths:
        - coverage/*
        - examples/* 
        - tests/*
        - vendor/*
checks:
  php: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 2