language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

install:
  - composer install

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover/coverage.xml